#!/usr/bin/env bash

echo ---------------------------------------------------------------
echo
echo Hello Human
echo Let''s build your electron app
echo
echo ---------------------------------------------------------------
echo
echo Running grunt build
echo

grunt build

echo
echo ---------------------------------------------------------------
echo
echo Done!
