#!/usr/bin/env bash

echo ---------------------------------------------------------------
echo
echo Hello Human
echo Let''s see some science!
echo
echo ---------------------------------------------------------------
echo

electron .

echo
echo ---------------------------------------------------------------
echo
echo Done!
